version: '3'
services:
  # geo-postgres-compose:
  #   container_name: 'geo-postgres-compose'
  #   image: geographica/postgis:dev_diplodocus
  #   environment:
  #     - POSTGRES_PASSWD=postgres
  #   ports:
  #     - "5432:5432"
  #   volumes:
  #     - ${LOCAL_DATABASE}:/data
  #     - ./data:/data_import 
  #   networks:
  #     - geo-postgres-compose-network
  # THIS IS THE CONNEXION WITH GOOGLE SQL INSTANCE
  geo-postgres-compose:
    container_name: "geo-postgres-compose"
    image: gcr.io/cloudsql-docker/gce-proxy:1.16
    # Port: MySQL (3306), PostgreSQL (5433)
    command: /cloud_sql_proxy -instances=skydipper-196010:europe-west1:skydipper-pg-1=tcp:0.0.0.0:5433 -credential_file=/config
    volumes:
      - ./sqlPrivateKey.json:/config
    ports:
      - "5434:5433"
    networks:
      - geo-postgres-compose-network
    restart: always
  
  geo-pgadmin-compose:
    container_name: 'geo-pgadmin-compose'
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: "test@vizzuality.com"
      PGADMIN_DEFAULT_PASSWORD: "PgAdmin2019!"
    volumes:
      - ./data:/data
    ports:
      - "16543:80"
    depends_on:
      - geo-postgres-compose
    networks:
      - geo-postgres-compose-network

  geopredictor_service:
    container_name: 'geopredictor_service'
    build: .
    ports:
      - "6767:6767"
    command: develop
    volumes:
      - ./GeoPredictor:/api/GeoPredictor
    depends_on:
    - geo-postgres-compose
    - geo-pgadmin-compose
    networks:
      - geo-postgres-compose-network
    restart: always
    env_file:
      - .env
    environment:
      PORT: 6767
      HOST: "0.0.0.0"
      database: test
      CT_REGISTER_MODE: auto
      ENVIRONMENT: dev
      DEBUG: "True"
      CT_TOKEN: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjU4MjBhZDk0NjlhMDI4Nzk4MmY0Y2QxOCIsInByb3ZpZGVyIjoibG9jYWwiLCJwcm92aWRlcklkIjpudWxsLCJlbWFpbCI6InNlcmdpby5nb3JkaWxsb0B2aXp6dWFsaXR5LmNvbSIsInJvbGUiOiJBRE1JTiIsImNyZWF0ZWRBdCI6IjIwMTYtMTEtMDdUMTY6MzY6MzYuODY4WiIsImV4dHJhVXNlckRhdGEiOnsiYXBwcyI6WyJnZnciLCJwcmVwIiwiYXF1ZWR1Y3QiLCJmb3Jlc3QtYXRsYXMiLCJydyIsImRhdGE0c2RnIl19fQ.3GzuhG8wD4gI5Fo6NTqHC_Dq6ChKPPWXygga2mAuKZw
      API_VERION: v1
      user: postgres
      password: postgres
      psqlPort: 5432

networks: 
  geo-postgres-compose-network:
    driver: bridge
 