version: '3'
services:
  GeoPredictor:
    build: .
    ports:
      - "6868:6868"
    command: develop
    volumes:
      - "./GeoPredictor:/GeoPredictor/GeoPredictor"
     depends_on:
    - postgres-compose
    - pgadmin-compose
    networks:
      - postgres-compose-network
    restart: always
    environment:
      PORT: 6868
      HOST: "0.0.0.0"
      database: test
      user: postgres
      password: postgres
      psqlPort: 5432
  postgres-compose:
    container_name: 'GeoPredictor-pdb'
    image: geographica/postgis:dev_diplodocus
    environment:
      POSTGRES_PASSWD: "postgres"
    ports:
      - "5432:5432"
    expose:
        - '5432'
    volumes:
      - ${LOCAL_DATABASE}:/data 
    networks:
      - postgres-compose-network
  pgadmin-compose:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: "test@vizzuality.com"
      PGADMIN_DEFAULT_PASSWORD: "PgAdmin2019!"
    ports:
      - "16543:80"
    depends_on:
      - postgres-compose
    networks:
      - postgres-compose-network
networks: 
  postgres-compose-network:
    driver: bridge