apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  namespace: default
  name: geopredictor
spec:
  scaleTargetRef:
    apiVersion: apps/v1beta1
    kind: Deployment
    name: geopredictor
  minReplicas: 1
  maxReplicas: 2
  targetCPUUtilizationPercentage: 50
